In [1]:
import numpy as np
import pandas as pd
import numpy as np

pd.__version__

'2.2.2'

In [2]:
data = pd.DataFrame({
        'zone': ['A','B','C','A','C','B','A','D','A','B','C','A'],
        'price': [3,6,12,4,10,5,2,14,3,7,11,4]
    })
data

zone  price
0     A      3
1     B      6
2     C     12
3     A      4
4     C     10
5     B      5
6     A      2
7     D     14
8     A      3
9     B      7
10    C     11
11    A      4

In [3]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

# creating one hot encoder object with categorical feature 0
# indicating the first column
columnTransformer = ColumnTransformer([('encoder',
                                        OneHotEncoder(),
                                        [0])],
                                      remainder='passthrough')

data_onehot=columnTransformer.fit_transform(data)
print(data_onehot)

[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0.  6.]
 [ 0.  0.  1.  0. 12.]
 [ 1.  0.  0.  0.  4.]
 [ 0.  0.  1.  0. 10.]
 [ 0.  1.  0.  0.  5.]
 [ 1.  0.  0.  0.  2.]
 [ 0.  0.  0.  1. 14.]
 [ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0.  7.]
 [ 0.  0.  1.  0. 11.]
 [ 1.  0.  0.  0.  4.]]


In [4]:
le = LabelEncoder()
data['zone'] = le.fit_transform(data['zone'])
data

zone  price
0      0      3
1      1      6
2      2     12
3      0      4
4      2     10
5      1      5
6      0      2
7      3     14
8      0      3
9      1      7
10     2     11
11     0      4